name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: |
          yarn install

      - name: End-to-end tests
        uses: cypress-io/github-action@v2
        with:
          build: false
          start: yarn preview
          wait-on: http://localhost:3000

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
